### ISSUE TITLE
java.sql.SQLTransientConnectionException: HikariPool - Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by degtevO** [tpolecat/doobie#1134]
First of all, `Doobie` is great. Thanks for this.
But I have a problem with `0.8.8` (also catched in `0.6.0`).

I have a small utility, witch just takes data from some db, and moving it to another. At the same time, it stores some metadata about moved data. So, I have 3 transactors, composed in the single resource. Each of them created like this:
```
val poolSize = 30

def postgresTransactor(conf: PostgresConf, bec: Blocker): Resource[Task, HikariTransactor[Task]] =
    for {
      ce <- ExecutionContexts.fixedThreadPool[Task](poolSize)
      xa <- HikariTransactor.newHikariTransactor[Task](
        conf.driver, conf.uri, conf.user, conf.password, ce, bec)

    } yield xa
```
I am inserting data in the consumer db via `updateMany`:

```
val sql ="insert ..."

Update[SomeEntity](sql).updateMany(someValuesList).transact(xa)
```
Some statistics:
About 4000 rows at single `updateMany`, 54 `updateMany`'s in parallel threads. ~200 000 inserted rows.

The utility runs daily by cron. Sometimes writing data ends with:
```
java.sql.SQLTransientConnectionException: HikariPool-3 - Connection is not available, request timed out after 30000ms.
                at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
                at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
                at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
                at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
                at doobie.util.transactor$Transactor$fromDataSource$FromDataSourceUnapplied.$anonfun$apply$14(transactor.scala:280)
                at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
                at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:222)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
```
It is not regular, I cannot find a cause for now. Consumer db serves an another app, so it can be busy sometimes.
Any workaround?

**Comment by zsambek** [comment]
@degtevO What are the stats of the HikariPools? How many threads are idle when you receive this exception?

**Comment by degtevO** [comment]
I am not sure, how I can check it?

**Comment by zsambek** [comment]
@degtevO You should enable HikariCP's debug logs. Then you should see similar logs: 
(total=5, active=5, idle=0, waiting=2)

**Comment by jatcwang** [comment]
Seems like the questions is answered so I'm closing this issue. Feel free to reply if it isn't, or you can ask in https://gitter.im/tpolecat/doobie
