### ISSUE TITLE
Apply[Read].tupleN methods read values in the reverse order

### ISSUE THREAD

**Issue by dylemma** [tpolecat/doobie#1256]
Example:

```scala
val result1 = sql"SELECT 'hi', 3".query[(String, Int)].unique.transact(xa).unsafeRunSync
println(s"Result 1: $result1")

val explicitRead = Apply[Read].tuple2(Read[String], Read[Int])
println(s"REVERSO: ${Read[(String, Int)].gets == explicitRead.gets.reverse}")

val result2 = sql"SELECT 'hi', 3".query[(String, Int)](explicitRead).unique.transact(xa).unsafeRunSync
println(s"Result 2: $result2")
```

Output:
```text
Result 1: (hi,3)
REVERSO: true
Exception in thread "main" java.sql.SQLException: Out of range value for column 'hi' : value hi
	at org.mariadb.jdbc.internal.com.read.resultset.rowprotocol.TextRowProtocol.getInternalLong(TextRowProtocol.java:346)
	at org.mariadb.jdbc.internal.com.read.resultset.rowprotocol.TextRowProtocol.getInternalInt(TextRowProtocol.java:252)
	at org.mariadb.jdbc.internal.com.read.resultset.SelectResultSet.getInt(SelectResultSet.java:981)
	at doobie.util.meta.MetaInstances.$anonfun$IntMeta$1(meta.scala:172)
        ...
```

**Comment by tpolecat** [comment]
I think `ap` is probably just backwards. It's easy to mix up.
