### ISSUE TITLE
Time support with MySQL JDBC 

### ISSUE THREAD

**Issue by kubum** [tpolecat/doobie#1275]
Using MySQL JDBC driver a program crashes at runtime while attempting read or write java time objects such as `OffsetDateTime` and `ZonedDateTime`. 

An example:

```scala
import java.time.{OffsetDateTime, ZonedDateTime}

import cats.effect._
import doobie._
import doobie.implicits._
import doobie.implicits.javatime._

object Main extends IOApp {
  override def run(args: List[String]) = {
    val xa = Transactor.fromDriverManager[IO](
      "com.mysql.cj.jdbc.Driver",
      "jdbc:mysql://localhost:3306/doobie",
      "root",
      ""
    )

    val createDatabase =
      sql"""
           |CREATE DATABASE IF NOT EXISTS doobie_test
     """.stripMargin.update

    val dropTable =
      sql"""
           |DROP TABLE IF EXISTS java_time_test
     """.stripMargin.update

    val createTable =
      sql"""
           |CREATE TABLE java_time_test (
           |  column1 datetime
           |)
     """.stripMargin.update

    def insertODT(now: OffsetDateTime) =
      sql"""
           |INSERT INTO java_time_test (column1) VALUES ($now)
     """.stripMargin.update

    def insertZDT(now: ZonedDateTime) =
      sql"""
           |INSERT INTO java_time_test (column1) VALUES ($now)
     """.stripMargin.update

    val query = sql"""SELECT * FROM java_time_test"""
      .query[OffsetDateTime]
      .stream
      .compile
      .toList

    val program = for {
      _ <- createDatabase.run
      _ <- dropTable.run
      _ <- createTable.run
      _ <- insertODT(OffsetDateTime.now).run
      _ <- insertZDT(ZonedDateTime.now).run
      result <- query
    } yield result

    program.transact(xa).map(println).as(ExitCode.Success)
  }
}
```

### Writing Stacktrace

```scala
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect datetime value: '\xAC\xED\x00\x05sr\x00\x0Djava.time.Ser\x95]\x84\xBA\x1B"H\xB2\x0C\x00\x00xpw\x0F\x0A\x00\x00\x07\xE4\x09\x15\x153*\x16\x14%8\x0' for column 'column1' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeUpdate$5(kleisliinterpreter.scala:958)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeUpdate$5$adapted(kleisliinterpreter.scala:958)
	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:112)
	at blockOn$extension @ doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$create$1(transactor.scala:344)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
```

### Reading Stacktrace

```scala
java.sql.SQLException: Conversion not supported for type java.time.OffsetDateTime
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1391)
	at doobie.util.meta.TimeMetaInstances.$anonfun$JavaOffsetDateTimeMeta$1(timemeta.scala:58)
	at doobie.util.meta.TimeMetaInstances.$anonfun$JavaOffsetDateTimeMeta$1$adapted(timemeta.scala:58)
	at doobie.util.Get.unsafeGetNonNullable(get.scala:30)
	at doobie.util.Read$.$anonfun$fromGet$1(read.scala:75)
	at doobie.util.Read$.$anonfun$fromGet$1$adapted(read.scala:75)
	at doobie.hi.resultset$.$anonfun$getNextChunkV$1(resultset.scala:192)
	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:112)
	at blockOn$extension @ doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$create$1(transactor.scala:344)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
```

Dependencies:
```
libraryDependencies ++= Seq(
  "org.typelevel" %% "cats-core" % "2.1.1",
  "org.typelevel" %% "cats-effect" % "2.2.0",
  "org.tpolecat" %% "doobie-core" % "0.9.0",
  "org.tpolecat" %% "doobie-hikari" % "0.9.0", 
  "mysql" % "mysql-connector-java" % "8.0.21"
)
```

docker-compose.yml:

```yml
version: '3.3'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=doobie
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      - "3306:3306"
```

### Background

MySQL JDBC connector expects it to be read as `java.sql.Timestamp` according to the [docs](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html). 

### Current workaround

Based on the Timestamp meta as the JDBC doc suggests, we get it first and the stick UTC on it:

```scala
trait DoobieJavaTimeInstances {
  import doobie.implicits.javasql.TimestampMeta

  implicit val mysqljdbcOffsetDateTIme: Meta[OffsetDateTime] =
    TimestampMeta.imap(ts => OffsetDateTime.ofInstant(ts.toInstant, ZoneOffset.UTC))(offsetDateTime =>
      java.sql.Timestamp.from(offsetDateTime.toInstant)
    )
}
```

### Discussion

For beginners this behaviour will likely to cause confusion. I wonder if we should have a pragmatic doobie package for MySQL defaults, even they aren't perfect, or a section in the documentation? What do you think?

Many thanks!

**Comment by Daenyth** [comment]
If you import `import doobie.implicits.javasql._` instead of `import doobie.implicits.javatime._` does it then work as expected?

I think this is likely just a matter of cleaning up the documentation.

See also #1236

**Comment by kubum** [comment]
@Daenyth thanks for the suggestion!`doobie.implicits.javasql._` doesn't define `OffsetDateTime` and others. It fails at compile time with following message:

```
type mismatch;
 found   : java.time.OffsetDateTime
 required: doobie.syntax.SqlInterpolator.SingleFragment
           |INSERT INTO java_time_test (column1) VALUES ($now)
```

In the "Current workaround" section `doobie.implicits.javasql.TimestampMeta` from there is used as a base for the converter to Java Time objects. 

I previously used doobie with postgres and everything was great. However, now I need to connect to MySQL, and I feel like we can improve the experience of using doobie with it too.

**Comment by Daenyth** [comment]
> doesn't define OffsetDateTime

Based on my reading here, I think that's actually correct: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

The mysql TIMESTAMP column stores data in UTC. It accepts inputs in any time zone, and then for storage, it converts your input data into the configured `time_zone`, stores that as utc, and then when you query it back out, it converts it back to the configured `time_zone`.

The part that makes me fairly certain of the behavior above is this:

> By default, the current time zone for each connection is the server's time. The time zone can be set on a per-connection basis. As long as the time zone setting remains constant, you get back the same value you store. If you store a TIMESTAMP value, and then change the time zone and retrieve the value, the retrieved value is different from the value you stored.

So I think in this case, it's not working out of the box because it isn't supposed to - an OffsetDateTime is not capable of modeling a mysql TIMESTAMP column.

I'll defer to @tpolecat on this from here; he's certainly more experienced than me with this and may be able to clarify further or point out where I'm incorrect if needed

**Comment by Daenyth** [comment]
I think it probably makes sense to close this as "wontfix"

**Comment by tpolecat** [comment]
Just to be clear here, if the column is of type `TIMESTAMP` then what you get is a moment in time that should map to `Instant`. There is no timezone or offset information.

In Postgres you can have `TIMESTAMP WITH TIME ZONE` which differs in that it will parse the timezone out of the date and perform offsetting to move it to UTC before storage. So this can map to `OffsetDateTime` where the offset on _read_ is always zero. I don't think MySQL has such a thing.

**Comment by kubum** [comment]
@Daenyth @tpolecat thank you for taking a look into it, i fully agree with you both. I went through the same discovery before creating this issue. Yes, unfortunately, MySQL doesn't store information about time zone same as it is possible with Postgres. Types with a zone are not a good fit. 

About doobie, I wondered if you think the documentation should help navigating MySQL users? They don't get compiler errors and `IOChecker` perfectly passes when `import doobie.implicits.javatime._` is in scope. The name of the import and [type signatures](https://github.com/tpolecat/doobie/blob/09ca01a9adc9bae63c4ca1bef4bbb2695bd0ca10/modules/core/src/main/scala/doobie/util/meta/timemeta.scala#L47-L51) in `TimeMetaInstances` might lead a beginner thinking it is universally useful for all adapters, but it won't work for some. However, I am happy to admit it is ok as it if you think it is an unreasonable expectation. Just thought to improve the docs.

**Comment by jatcwang** [comment]
Feels like maybe we should remove remove the default `OffsetDateTime` and `ZonedDateTime` instances instead.

As a user, if I insert something into the DB I expect to get the same thing back assuming there are no triggers but these instances breaks it because it resets the offset/zone.

We can probably provide a Read/Write for these types which internally spans two columns (TIMEZONETZ, TEXT)

**Comment by tpolecat** [comment]
You can't expect round-tripping to work in general. Strings will get truncated if they're inserted into CHAR columns for instance; timestamps with nanos will typically get rounded to microseconds; etc. That's not something we can guarantee.

**Comment by jatcwang** [comment]
Yeah true good examples!
