### ISSUE TITLE
Feature request: Better errors for unique, nel and option

### ISSUE THREAD

**Issue by erikvanoosten** [tpolecat/doobie#1493]
### Context

I have production log full of exceptions that look like:

```
d.u.invariant$UnexpectedContinuation$: Expected ResultSet exhaustion, but more rows were available.
	at d.u.invariant$UnexpectedContinuation$.<clinit>(invariant.scala:30)
	at doobie.hi.resultset$.$anonfun$getOption$1(resultset.scala:218)
	at cats.free.Free.step(Free.scala:56)
	at cats.free.Free.$anonfun$foldMap$1(Free.scala:159)
	at c.d.KleisliFlatMap.$anonfun$tailRecM$2(Kleisli.scala:624)
	at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:16)
	at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:15)
	at z.i.CatsMonadError.tailRecM(cats.scala:274)
	at cats.StackSafeMonad.$anonfun$tailRecM$1(StackSafeMonad.scala:17)
	at z.i.FiberContext.evaluateNow(FiberContext.scala:914)
	at z.i.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at j.u.c.ThreadPoolExecutor.runWorker(Unknown Source)
	at j.u.c.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

But i am already spending more then an hour just to find out which query this is about.

### The request

Add methods `.unique(string)`, `.net(string)` and `.option(string)` that uses the given string in the raised error.

**Comment by erikvanoosten** [comment]
Until Doobie provides this out of the box you can use thishelper class instead. It is less efficient because it loads the entire results set even when this is not necessary.

```
import cats.data.NonEmptyList
import cats.implicits._
import doobie.ConnectionIO
import doobie.free.connection.AsyncConnectionIO

object DoobieTools {

  case class UnexpectedEnd(location: String) extends Exception(s"ResultSet exhausted; more rows expected: $location")
  case class UnexpectedContinuation(location: String)
      extends Exception(s"Expected ResultSet exhaustion, but more rows were available: $location")

  implicit class QueryWithBetterOptionUniqueAndNel[A](val query: doobie.Query0[A]) {

    /**
      * Like [[doobie.util.query.Query0#unique()]] but with a more specific error message.
      *
      * @param location information about where the query was performed, e.g.: table name, method name, etc.
      */
    def unique(location: => String): ConnectionIO[A] = {
      query
        .to[List]
        .flatMap {
          case a :: Nil => a.pure[ConnectionIO]
          case Nil      => AsyncConnectionIO.raiseError(UnexpectedEnd(location))
          case _        => AsyncConnectionIO.raiseError(UnexpectedContinuation(location))
        }
    }

    /**
      * Like [[doobie.util.query.Query0#option()]] but with a more specific error message.
      *
      * @param location information about where the query was performed, e.g.: table name, method name, etc.
      */
    def option(location: => String): ConnectionIO[Option[A]] = {
      query
        .to[List]
        .flatMap {
          case a :: Nil => a.some.pure[ConnectionIO]
          case Nil      => Option.empty[A].pure[ConnectionIO]
          case _        => AsyncConnectionIO.raiseError(UnexpectedContinuation(location))
        }
    }

    /**
      * Like [[doobie.util.query.Query0#nel()]] but with a more specific error message.
      *
      * @param location information about where the query was performed, e.g.: table name, method name, etc.
      */
    def nel(location: => String): ConnectionIO[NonEmptyList[A]] = {
      query
        .to[List]
        .flatMap { list =>
          NonEmptyList.fromList(list) match {
            case Some(nel) => nel.pure[ConnectionIO]
            case None      => AsyncConnectionIO.raiseError(UnexpectedEnd(location))
          }
        }
    }
  }

}
```

**Comment by jatcwang** [comment]
Since it raises an error inside the IO, do you think cats-effect IO's tracing support https://typelevel.org/cats-effect/docs/2.x/guides/tracing will help?

**Comment by erikvanoosten** [comment]
No idea, I don't know about that project. I am using doobie with ZIO. Personally I'd rather not mix zio and cats anymore then necessary; it gets complicated very fast.

**Comment by jatcwang** [comment]
ZIO has it too (I think it had it before cats-effect). https://youtu.be/mGxcaQs3JWI?t=3111

I couldn't find detailed doc on it, but iir it's a system property you can use to turn it on. (Or maybe it's on by default?)

**Comment by jatcwang** [comment]
with .queryWithlabel/.updateWithLabel + LogHandler which is a bit more general than your suggestion, I think this is solved now.
