### ISSUE TITLE
Exception running shapeless examples from Book

### ISSUE THREAD

**Issue by yatesco** [tpolecat/doobie#1619]
Hi there,

I'm following the book but when I run the steps from https://tpolecat.github.io/doobie/docs/04-Selecting.html I get the following stack trace:

```scala
val y: doobie.util.yolo.Yolo[cats.effect.IO] = doobie.util.yolo$Yolo@138174a4
import y._

import shapeless._
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1cdd7413[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@b51cce9[Wrapped task = org.jetbrains.jps.incremental.scala.remote.AsynchEventGenerator$$anon$1@76c2d729]] rejected from java.util.concurrent.ThreadPoolExecutor@51d00526[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 140]
  at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
  at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
  at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
  at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
  at org.jetbrains.jps.incremental.scala.remote.AsynchEventGenerator.listener(AsynchEventGenerator.scala:9)
  at org.jetbrains.jps.incremental.scala.remote.EventGeneratingClient.publishEvent(EventGeneratingClient.scala:18)
  at org.jetbrains.jps.incremental.scala.remote.EventGeneratingClient.worksheetOutput(EventGeneratingClient.scala:72)
  at org.jetbrains.jps.incremental.scala.local.worksheet.WorksheetServer$RedirectToClientOutputStream.flush(WorksheetServer.scala:88)
  at org.jetbrains.jps.incremental.scala.local.worksheet.WorksheetServer$RedirectToClientOutputStream.write(WorksheetServer.scala:69)
  at java.base/java.io.OutputStream.write(OutputStream.java:157)
  at java.base/java.io.PrintStream.write(PrintStream.java:559)
  at java.base/java.io.PrintStream.write(PrintStream.java:559)
  at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
  at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
  at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
  at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:181)
  at java.base/java.io.PrintStream.newLine(PrintStream.java:625)
  at java.base/java.io.PrintStream.println(PrintStream.java:900)
  at com.martiansoftware.nailgun.ThreadLocalPrintStream.println(ThreadLocalPrintStream.java:227)
  at scala.Console$.println(Console.scala:268)
  at doobie.util.yolo$Yolo.$anonfun$out$1(yolo.scala:30)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at cats.effect.IOFiber.runLoop(IOFiber.scala:383)
  at cats.effect.IOFiber.afterBlockingSuccessfulR(IOFiber.scala:1162)
  at cats.effect.IOFiber.run(IOFiber.scala:129)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:359)
```

specifically, running the following code:
```scala
import shapeless._
sql"select code, name, population, gnp from country"
  .query[String :: String :: Int :: Option[Double] :: HNil]
  .stream
  .take(5)
  .quick
  .unsafeRunSync()
```

I'm doing this through an IntelliJ Scala worksheet in a 2.13.7 Scala project using 1.0.0RC1:
```scala
import doobie._
import doobie.implicits._
import cats._
import cats.effect._
import cats.implicits._
import doobie.util.ExecutionContexts
import cats.effect.unsafe.implicits.global

// A transactor that gets connections from java.sql.DriverManager and executes blocking operations
// on an our synchronous EC. See the chapter on connection handling for more info.
val xa = Transactor.fromDriverManager[IO](
  "org.postgresql.Driver",     // driver classname
  "jdbc:postgresql:world",     // connect URL (driver-specific)
  "postgres",                  // user
  ""                           // password
)
def  runIt[T](program: doobie.ConnectionIO[T]): T = {
  val io = program.transact(xa)
  io.unsafeRunSync()
}

val program1: doobie.ConnectionIO[Int] = 42.pure[ConnectionIO]
runIt(program1)

val program = sql"select 42".query[Int].unique
runIt(program)

runIt(for {
  a <- sql"select 42".query[Int].unique
  b <- sql"select random()".query[Double].unique
} yield(a,b))

runIt(sql"select name from country"
  .query[String]    // Query0[String]
  .to[List]         // ConnectionIO[List[String]]
)       // List[String]

val y = xa.yolo // a stable reference is required
import y._

import shapeless._
sql"select code, name, population, gnp from country"
  .query[String :: String :: Int :: Option[Double] :: HNil]
  .stream
  .take(5)
  .quick
  .unsafeRunSync()

```

**Comment by jatcwang** [comment]
I think this may be related to https://youtrack.jetbrains.com/issue/SCL-18639. I think I've experienced issues in the past with running multi-threaded code in worksheet too so I tend to do any experiment in a fresh sbt project.

**Comment by yatesco** [comment]
Thanks @jatcwang
