### ISSUE TITLE
[SqlLite] munit check fails on insert, but works on select

### ISSUE THREAD

**Issue by benkio** [tpolecat/doobie#1782]
Hi,
I created a simple project to reproduce the error. Just run `test` to see the problem
[doobiesqlite.tar.gz](https://github.com/tpolecat/doobie/files/10087101/doobiesqlite.tar.gz)

I have a simple table with just a column of type `BIGINT` and a case class with a `Long` field
When I check the `SELECT` it works fine, but the `INSERT` fails with 

```
  INSERT INTO test VALUES (?)
  ✓ SQL Compiles and TypeChecks
  ✕ P01 Long  →  VARCHAR (VARCHAR)
    Long is not coercible to VARCHAR (VARCHAR) according to the JDBC
    specification. Expected schema type was BIGINT.
``` 

It seems that the `BIGINT` turn out to be a `VARCHAR` for some reason.

PS Sqllite doesn't have `BIGINT`, but it's automatically mapped to `INTEGER`

**Comment by benkio** [comment]
I have a bigger and more up to date project I can try this out (and it's where I've found the issue in the first place), I'll give it a try and eventually come back here to either close or follow up

**Comment by benkio** [comment]
I updated the project above to latest versions.
I attach it here

Here the schema of the db, included in the zip
```
db.sqlite3> .schema
.schema
+--------------------------------------------------------+
| sql                                                    |
+--------------------------------------------------------+
| CREATE TABLE test_data(id BIGINT PRIMARY KEY NOT NULL) |
+--------------------------------------------------------+
Time: 0.006s
```

However, now the insert doesn't even typecheck:

```
TestCodeSpec:
==> X TestCodeSpec.query check  0.347s munit.FailException: src/test/scala/TestCodeSpec.scala:25
24:    checkOutput(TestCode.query)
25:    check(TestCode.insert(TestData(2)))
26:  }
  Update0 defined at TestCode.scala:12
  INSERT INTO test_data VALUES (?)
  ✕ SQL Compiles and TypeChecks
    No parameter has been set yet
    at munit.Assertions.fail(Assertions.scala:256)
    at munit.Assertions.fail$(Assertions.scala:24)
    at munit.FunSuite.fail(FunSuite.scala:13)
    at doobie.munit.analysisspec$Checker.checkImpl(analysisspec.scala:60)
    at doobie.munit.analysisspec$Checker.check(analysisspec.scala:34)
    at doobie.munit.analysisspec$Checker.check$(analysisspec.scala:32)
    at TestCodeSpec.check(TestCodeSpec.scala:9)
    at TestCodeSpec.$init$$$anonfun$1(TestCodeSpec.scala:25)
Caused by: doobie.munit.analysisspec$Checker$ErrorItems
    at doobie.munit.analysisspec$Checker$ErrorItems$.apply(analysisspec.scala:66)
    at doobie.munit.analysisspec$Checker.checkImpl(analysisspec.scala:59)
... 4 more
```

Maybe I'm doing something wrong 🤷
I've tried in the bigger project as well and I get the same exact error of the initial message.
The jdbc-sqlite didn't fix it

[doobiesqlite.tar.gz](https://github.com/user-attachments/files/23531376/doobiesqlite.tar.gz)
