### ISSUE TITLE
Getting error with update.

### ISSUE THREAD

**Issue by wpoosanguansit** [tpolecat/doobie#185]
I think I am still missing something while following the example in the book.  I keep getting the following error:

[pool-1-thread-3] ERROR org.http4s.blaze.pipeline.Stage - Error running route: Request(POST,/meta,HTTP/1.1,Headers(Host: localhost:8000, Connection: keep-alive, Content-Length: 16322, Accept: application/json, text/javascript, */*; q=0.01, Origin: http://localhost:8000, X-Requested-With: XMLHttpRequest, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36, Content-Type: application/x-www-form-urlencoded; charset=UTF-8, Referer: http://localhost:8000/meta, Accept-Encoding: gzip, deflate, Accept-Language: en-US,en;q=0.8, Cookie: JSESSIONID=1plfpmg0la8fs5wyhba3wod94),Await(scalaz.concurrent.Task@6191f8ce,<function1>),org.http4s.AttributeMap@e7065ec)
java.sql.SQLException: Parameter index out of range (3 > number of parameters, which is 2).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3399)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3384)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3421)
	at com.mysql.jdbc.PreparedStatement.setLong(PreparedStatement.java:3438)
	at doobie.free.preparedstatement$$anon$3$$anonfun$apply$85.apply(preparedstatement.scala:1030)
	at doobie.free.preparedstatement$$anon$3$$anonfun$apply$85.apply(preparedstatement.scala:1030)
	at doobie.free.preparedstatement$$anon$3$$anonfun$primitive$1$$anonfun$apply$1.apply(preparedstatement.scala:936)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)

from the update statement:

sql"""UPDATE test
          SET str = $t.str
          WHERE id = $t.id""".update.withGeneratedKeys[TestJson]("id", "str")

I basically took out the sql from the book and just change the table names to try things out.  Thank you for your help.

**Comment by tpolecat** [comment]
A few things. You need to properly quote your interpolated values: `${t.str}`, and I don't think SQL supports returning generated keys, so you'll have to use the equivalent of the first example under [Retrieving Results](http://tpolecat.github.io/doobie-0.2.2/07-Updating.html) to retrieve the generated key and then do another select.

**Comment by wpoosanguansit** [comment]
Got it.  Thanks for your help.
