### ISSUE TITLE
h2 doesn't support 'withGeneratedKeys' with multiple columns

### ISSUE THREAD

**Issue by j-keck** [tpolecat/doobie#225]
from [org/h2/jdbc/JdbcConnection.java#L1165](https://github.com/h2database/h2database/blob/86462170cd0c77bd07cfa40a7a14981032e2eacf/h2/src/main/org/h2/jdbc/JdbcConnection.java#L1165):
>     * Creates a new prepared statement.
>     * This method just calls prepareStatement(String sql) internally.
>     * The method getGeneratedKeys only supports one column.
>     *
>     * @param sql the SQL statement
>     * @param columnNames ignored
>     * @return the prepared statement
>     * @throws SQLException
>     *             if the connection is closed

should at least be noted somewhere.

----

this code:
```
  val xa = DriverManagerTransactor[Task](
      "org.h2.Driver", "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "sa", ""
    )

  val setup: ConnectionIO[Int] = sql"""
     CREATE TABLE person (
       id      IDENTITY PRIMARY KEY,
       name    VARCHAR
     )""".update.run

  case class Person(id: Long, name: String)

  def insertPerson(person: Person): ConnectionIO[Person] =
    sql"INSERT INTO person (name) VALUES (${person.name})"
      .update.withUniqueGeneratedKeys[Person]("id", "name")



  setup *> insertPerson(Person(0, "the-name")) transact(xa) run
```
throws:
```
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Invalid value "2" for parameter "columnIndex" [90008-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:215)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:2934)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:2962)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:275)
	at doobie.free.resultset$ResultSetOp$GetString1$$anonfun$defaultTransK$85.apply(resultset.scala:366)
	at doobie.free.resultset$ResultSetOp$GetString1$$anonfun$defaultTransK$85.apply(resultset.scala:366)
	at doobie.free.resultset$ResultSetOp$$anonfun$primitive$1$$anonfun$apply$1.apply(resultset.scala:90)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
	at scalaz.concurrent.Task$.Try(Task.scala:379)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
	at scalaz.concurrent.Future.step(Future.scala:111)
	at scalaz.concurrent.Future.listen(Future.scala:76)
	at scalaz.concurrent.Future.runAsync(Future.scala:143)
	at scalaz.concurrent.Future.run(Future.scala:160)
	at scalaz.concurrent.Task.run(Task.scala:97)
	at Main$.delayedEndpoint$Main$1(Main.scala:27)
	at Main$delayedInit$body.apply(Main.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$.main(Main.scala:7)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by tpolecat** [comment]
Yeah this feature is only supported by some vendors (this is true in general for every JDBC operation) but I'll make it more clear in the doc. I think it doesn't work at all in MySQL.

**Comment by ianagius** [comment]
It didnt work for us either for mysql
