### ISSUE TITLE
java.util.NoSuchElementException: head of empty list in Ammonite-REPL

### ISSUE THREAD

**Issue by justinpitts** [tpolecat/doobie#258]
When I walk through the first tutorial, I get a failure message from Ammonite when I try to assign the expression 42.point[ConnectionIO] to program1.

Full session screenshot: http://imgur.com/8GOAih0

```
Full text of error: 
 val program1 = 42.point[ConnectionIO]
Compilation Failed
Main.scala:1430: exception during macro expansion:
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:420)
        at scala.collection.immutable.Nil$.head(List.scala:417)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.subst(TypeMaps.scala:709)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.substFor$1(TypeMaps.scala:717)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:732)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:685)
        at scala.collection.immutable.List.loop$1(List.scala:173)
        at scala.collection.immutable.List.mapConserve(List.scala:189)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:115)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:716)
        at scala.reflect.internal.Types$Type.subst(Types.scala:705)
        at scala.reflect.internal.Types$TypeApiImpl.substituteTypes(Types.scala:240)
        at scala.reflect.internal.Types$TypeApiImpl.substituteTypes(Types.scala:218)
        at derive.Derive$$anonfun$impl$1$3.apply(Derive.scala:80)
        at derive.Derive$$anonfun$impl$1$3.apply(Derive.scala:75)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
        at scala.collection.immutable.Set$Set3.foreach(Set.scala:145)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
        at derive.Derive.impl$1(Derive.scala:75)
        at derive.Derive.fleshedOutSubtypes(Derive.scala:84)
        at derive.Derive.derive$Derive$$onFail$1(Derive.scala:139)
        at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:207)
        at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:181)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
        at derive.Derive.derive$Derive$$rec$1(Derive.scala:181)
        at derive.Derive.deriveType(Derive.scala:220)
        at derive.Derive.derive(Derive.scala:58)
        at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:398)
        at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:398)

              .print(program1, program1, "program1", scala.None)

```

**Comment by tpolecat** [comment]
Ah, interesting. Ammonite doesn't like something about `ConnectionIO`. I'll chase it down.

Thanks for the thorough bug report!

**Comment by tpolecat** [comment]
A bit more information. The problem appears to be in the alias, not in the underlying type:

@ import doobie.imports._
import doobie.imports._

@ import scalaz._, Scalaz._
import scalaz._, Scalaz._

@ 42.point[ConnectionIO]
Compilation Failed
Main.scala:1426: exception during macro expansion: 
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.subst(TypeMaps.scala:709)
        ...
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at derive.Derive.derive$Derive$$rec$1(Derive.scala:181)
	at derive.Derive.deriveType(Derive.scala:220)
	at derive.Derive.derive(Derive.scala:58)
	at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:398)
	at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:398)

              .print(res2, res2, "res2", scala.None)
                    ^

// But it works ok with the unaliased type

@ 42.point[ConnectionIO] : Free[({ type l[a] = Coyoneda[FC.ConnectionOp, a] })#l, Int]
res2: Free[Coyoneda[FC.ConnectionOp, a], Int] = Return(42)

**Comment by tpolecat** [comment]
Hey @lihaoyi do you have any thoughts on this? Looks like something wacky with printing aliased types.

**Comment by lihaoyi** [comment]
Looks like https://github.com/lihaoyi/Ammonite/issues/198

Honestly, I have no clue what I'm doing, so the code inside pprint which is blowing up probably is just forgetting to handle some case somewhere or is buggy. If you have time, Add your test case [here](https://github.com/lihaoyi/upickle-pprint/blob/master/pprint/shared/src/test/scala/test/pprint/DerivationTests.scala) and see if you tweak it to not blow up =P

**Comment by tpolecat** [comment]
Cool, I'll take a look.

**Comment by justinpitts** [comment]
Appears to be fixed. Thanks @tpolecat and @lihaoyi
