### ISSUE TITLE
code will leak connections if using Option or unique and result does not meet expectations

### ISSUE THREAD

**Issue by asquassabia1** [tpolecat/doobie#464]
test("world db setup smoke test (*) (unique, fail)") {
    /*
      WHOOPS!

      org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-193]

    	at org.h2.message.DbException.get(DbException.java:179)
	    at org.h2.message.DbException.get(DbException.java:155)
  	  at org.h2.message.DbException.get(DbException.java:144)
  	  at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:184)
    	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:126)
  	  at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
    	at org.h2.Driver.connect(Driver.java:69)
    	at java.sql.DriverManager.getConnection(DriverManager.java:664)
    	at java.sql.DriverManager.getConnection(DriverManager.java:247)
    	at doobie.free.drivermanager$$anon$2$$anonfun$apply$9.apply(drivermanager.scala:207)
  	  at doobie.free.drivermanager$$anon$2$$anonfun$apply$9.apply(drivermanager.scala:207)
    	at doobie.util.iolite$IOLite$Primitive.unsafePerformIO(iolite.scala:58)
    	at doobie.util.iolite$IOLite$Compute.loop$1(iolite.scala:81)
  	  at doobie.util.iolite$IOLite$Compute.unsafePerformIO(iolite.scala:85)
    	at util.tutorial.doobie.WorldDbDoobieTest$$anonfun$6$$anonfun$1.apply$mcV$sp(WorldDbDoobieTest.scala:82)
    	at util.tutorial.doobie.WorldDbDoobieTest$$anonfun$6$$anonfun$1.apply(WorldDbDoobieTest.scala:79)
  	  at util.tutorial.doobie.WorldDbDoobieTest$$anonfun$6$$anonfun$1.apply(WorldDbDoobieTest.scala:79)

  	  LINE 79 at the time of the trace is marked below

     */
    val xa = transientDb.dmTransactor
    val ss: Query0[String] = sql"select name from country".query[String]
    /* LINE 79 */ val caught = intercept[InvariantViolation] {
      val aut: String = ss.unique // ConnectionIO[String]
        .transact(xa)
        .unsafePerformIO // String
    }
    assert(!caught.getMessage().isEmpty)
  }

**Comment by tpolecat** [comment]
Hm, this should not be possible. Can you paste a full reproduction?

**Comment by asquassabia1** [comment]
Thanks for being so prompt.  Hah.  Yesterday it was reproducing without fail, today I cannot get it to reproduce.  In context, this was one of a suite of tests with a single connection (i.e. not pooled): 

def dmTransactor():Transactor[IOLite] = /* doobie */ {
    logger.info("(dmTransactor) =>" + msg)
    DriverManagerTransactor[IOLite](
      driverString, connectionString, user, pwd
    )
  }

 (dmTransactor) =>connecting sa to RDBMS using org.h2.Driver with jdbc:h2:mem:world;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=1;TRACE_LEVEL_SYSTEM_OUT=<whatever>

Because of the in-memory nature of this instance of H2 I wonder speculatively if this is't some kind of race condition between H2 trying to garbage collect its presumably leftover open connection, and  doobie trying to close that same connection, but being preempted.  I suppose this can be marked as "cannot reproduce."  

Sorry for the inconvenience, truly.  Gah!

**Comment by tpolecat** [comment]
Hm, curious. An in-memory database with `DB_CLOSE_DELAY=-1` means every connection is going to the same db and it will live for the life of the JVM, so it's possible that through many test runs and failure and racing and so on in your sbt session maybe a connection got leaked somewhere. But doobie shouldn't ever allow that to happen so it's still suspicious. Please let me know if you see it again and I'll take a closer look.
