### ISSUE TITLE
Batch updating a huge list causes OOM

### ISSUE THREAD

**Issue by armundle** [tpolecat/doobie#466]
```
 type Map = (String, Int)
 type Maps = Vector[Map]
 def insertMany(ms: Maps): ConnectionIO[Int] = {
   println(s"map size: ${ms.size}") //2312213
   val sql = "insert into collection (key, value) values (?, ?)"
   Update[Map](sql)
     .updateMany(ms)
 }
```
Above code causes OOM with memory settings: `-Xms512m -Xmx1536m`:

```
java.lang.OutOfMemoryError: Java heap space
    at scalaz.InvariantFunctor$class.$init$(InvariantFunctor.scala:46)
    at scalaz.FreeInstances$$anon$3.<init>(Free.scala:424)
    at scalaz.FreeInstances.freeMonad(Free.scala:424)
    at doobie.util.composite$LowerPriorityComposite$$anon$7$$anonfun$14.apply(composite.scala:119)
    at doobie.util.composite$LowerPriorityComposite$$anon$7$$anonfun$14.apply(composite.scala:119)
    at doobie.util.composite$LowerPriorityComposite$$anon$6$$anonfun$11.apply(composite.scala:109)
    at doobie.util.composite$LowerPriorityComposite$$anon$6$$anonfun$11.apply(composite.scala:109)
    at doobie.util.composite$LowerPriorityComposite$$anon$6$$anonfun$11.apply(composite.scala:109)
    at doobie.util.composite$LowerPriorityComposite$$anon$6$$anonfun$11.apply(composite.scala:109)
    at doobie.util.composite$LowerPriorityComposite$$anon$8$$anonfun$17.apply(composite.scala:129)
    at doobie.util.composite$LowerPriorityComposite$$anon$8$$anonfun$17.apply(composite.scala:129)
    at doobie.hi.preparedstatement$.set(preparedstatement.scala:222)
    at doobie.hi.preparedstatement$$anonfun$addBatchesAndExecute$1.apply(preparedstatement.scala:88)
    at doobie.hi.preparedstatement$$anonfun$addBatchesAndExecute$1.apply(preparedstatement.scala:88)
    at scala.collection.immutable.List$$anonfun$foldRight$1.apply(List.scala:397)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at scala.collection.immutable.List.foldRight(List.scala:397)
    at doobie.hi.preparedstatement$.addBatchesAndExecute(preparedstatement.scala:88)
    at doobie.util.update$Update$class.updateMany(update.scala:113)
    at doobie.util.update$Update$$anon$5.updateMany(update.scala:198)
    at ...insertMany…
```

doobie-* versions:
```
[info] org.tpolecat:doobie-core_2.11:0.4.1
[info] org.tpolecat:doobie-hikari_2.11:0.4.1
[info] org.tpolecat:doobie-postgres_2.11:0.4.1
[info] org.typelevel:macro-compat_2.11:1.1.1
```

**Comment by armundle** [comment]
This is the current workaround:
```
fs.grouped(10000).toList.traverseU(insertMany(xa)).map(_.suml)
```

**Comment by tpolecat** [comment]
@n4to4 reports that it's also about 2x slower than Slick. See if we can optimize bulk inserts like we do with reads.

**Comment by wedens** [comment]
For bulk inserts `COPY` should perform better.

**Comment by tpolecat** [comment]
Aha, worth a try. I didn't know MySQL did that.

**Comment by wedens** [comment]
I'm don't think mysql has `COPY`. So, it's not portable. I think @armundle uses postgresql.

**Comment by vegansk** [comment]
Btw, mysql has multiple row insert syntax:
```sql
insert into test values (1, 'a'), (2, 'b'), ...
```
