### ISSUE TITLE
Fragment concatenation with constant and interpolated value

### ISSUE THREAD

**Issue by brinklec** [tpolecat/doobie#495]
I'm a beginner so I may be doing something stupid here, but it looks like the monoid for fragment concatenation is broken in 0.4.0 for Cats in a case that includes concatenation of a fragment containing a constant (e.g., for tablename) with a fragment containing an interpolated value.  Equivalent constructs with literals substituted for one or both of these work fine.

```scala
import doobie.imports._
import cats._, cats.data._, cats.implicits._
import fs2.interop.cats._, fs2.Task, fs2.Strategy
import shapeless._

Class.forName("oracle.jdbc.driver.OracleDriver")

val xa = DriverManagerTransactor[Task]("oracle.jdbc.driver.OracleDriver", "jdbc:oracle:thin:@SERVER:PORT:INSTANCE", "USER", "PASSWORD") 

// FRAGMENT WITH CONSTANT
def tbl(table: String) = fr"select count(*)/2 from" ++ Fragment.const(table)

// FRAGMENT WITH INTERPOLATED VALUE
def rel(relID: Int) = fr"where current_release_id = $relID"


// EQUIVALENT FROM TWO LITERALS CONCATENATES OK
val cnt = fr"select count(*)/2 from mbus_diff" ++ fr"where current_release_id = 25005"
val q = cnt.query[Int].unique
q.transact(xa).unsafeRun

// ONE LITERAL AND ONE INTERPOLATED VALUE ALSO WORKS
val cnt = fr"select count(*)/2 from mbus_diff" ++ rel(25005)
val q = cnt.query[Int].unique
q.transact(xa).unsafeRun

// ONE LITERAL AND ONE CONSTANT ALSO WORKS
val cnt = tbl("mbus_diff") // INCLUDES CONCATENATED LITERAL (SEE DEF ABOVE)
val q = cnt.query[Int].unique
q.transact(xa).unsafeRun

//  BUT FOLLOWING APPARENTLY EQUIVALENT FRAGMENT APPARTENTLY GENERATES INCORRECT SQL
val cnt = tbl("mbus_diff") ++ rel(25005)
val q = cnt.query[Int].unique
q.transact(xa).unsafeRun

// CONSOLE OUTPUT FOR ABOVE:
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

  at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
  at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
  at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
  at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
  at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
  at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
  at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:2
08)
  at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedState
ment.java:886)
  at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.jav
a:1175)
  at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.jav
a:1296)
  at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedSt
atement.java:3613)
  at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedState
ment.java:3657)
  at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePrepar
edStatementWrapper.java:1495)
  at doobie.free.preparedstatement$PreparedStatementOp$ExecuteQuery$$anonfun$def
aultTransK$23.apply(preparedstatement.scala:197)
  at doobie.free.preparedstatement$PreparedStatementOp$ExecuteQuery$$anonfun$def
aultTransK$23.apply(preparedstatement.scala:197)
  at doobie.free.preparedstatement$PreparedStatementOp$$anonfun$primitive$1$$ano
nfun$apply$1.apply(preparedstatement.scala:96)
  at fs2.Task$$anonfun$delay$1.apply(Task.scala:191)
  at fs2.Task$$anonfun$delay$1.apply(Task.scala:191)
  at fs2.Task$$anonfun$suspend$1$$anonfun$2.apply(Task.scala:199)
  at fs2.Task$$anonfun$suspend$1$$anonfun$2.apply(Task.scala:199)
  at fs2.util.Attempt$.apply(Attempt.scala:12)
  at fs2.Task$$anonfun$suspend$1.apply(Task.scala:199)
  at fs2.Task$$anonfun$suspend$1.apply(Task.scala:199)
  at fs2.internal.Future.step(Future.scala:54)
  at fs2.internal.Future.listen(Future.scala:30)
  at fs2.internal.Future.runAsync(Future.scala:69)
  at fs2.internal.Future.run(Future.scala:79)
  at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
  ... 42 elided
```

**Comment by tpolecat** [comment]
The problem is that the constant fragment is constructed with a literal string and no space is added after concatenation. You an print a fragment to see its SQL to make this clear. You can fix this by appending a space to the table name or prepending one to the `WHERE` clause.

```scala
scala> def tbl(table: String) = fr"select count(*)/2 from" ++ Fragment.const(table)
tbl: (table: String)doobie.util.fragment.Fragment

scala> def rel(relID: Int) = fr"where current_release_id = $relID"
rel: (relID: Int)doobie.util.fragment.Fragment

// no space before "where", oops
scala> tbl("mbus_diff") ++ rel(25005)
res0: doobie.util.fragment.Fragment = Fragment("select count(*)/2 from mbus_diffwhere current_release_id = ? ")

scala> def tbl(table: String) = fr"select count(*)/2 from" ++ Fragment.const(table + " ")
tbl: (table: String)doobie.util.fragment.Fragment

// ok
scala> tbl("mbus_diff") ++ rel(25005)
res1: doobie.util.fragment.Fragment = Fragment("select count(*)/2 from mbus_diff where current_release_id = ? ")
```

It's not clear that this is the best behavior. Perhaps there should be `const` and `const0` that mirror `fr` and `fr0` in terms of intermediate spacing.

Note also that `fr"where current_release_id = 25005"` is *not* equivalent to `rel(25005)`. Interpolated arguments are turned into `?` placeholders and the eventual JDBC program that's constructed will use `PreparedStatement.setInteger` to set the value (i.e., interpolated values are not just stuffed into the string).

**Comment by brinklec** [comment]
Beautiful and amazingly fast answer, thank you!!

**Comment by tpolecat** [comment]
Still open because `const` and `const0` and also need doc … I will probably do this.
