### ISSUE TITLE
NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z — when built with 2.12.2, 2.12.3

### ISSUE THREAD

**Issue by toby5box** [tpolecat/doobie#562]
When building with scala version 2.12.2 and 2.12.3, I get this crash when constructing a Transactor. (2.12.1 is OK)

```
java.lang.NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z
	at scala.reflect.internal.TypeDebugging$typeDebug$.<init>(TypeDebugging.scala:62)
	at scala.reflect.internal.SymbolTable.typeDebug$lzycompute$1(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.typeDebug(SymbolTable.scala:16)
	at scala.reflect.runtime.JavaUniverseForce.force(JavaUniverseForce.scala:54)
	at scala.reflect.runtime.JavaUniverseForce.force$(JavaUniverseForce.scala:6)
	at scala.reflect.runtime.JavaUniverse.force(JavaUniverse.scala:16)
	at scala.reflect.runtime.JavaUniverse.init(JavaUniverse.scala:147)
	at scala.reflect.runtime.JavaUniverse.<init>(JavaUniverse.scala:78)
	at scala.reflect.runtime.package$.universe$lzycompute(package.scala:17)
	at scala.reflect.runtime.package$.universe(package.scala:17)
	at doobie.util.meta$MetaInstances.$init$(meta.scala:357)
	at doobie.util.meta$Meta$.<init>(meta.scala:167)
	at doobie.util.meta$Meta$.<clinit>(meta.scala)
	at doobie.imports$.<init>(imports.scala:88)
	at doobie.imports$.<clinit>(imports.scala)
	at com.xx.service.Deploy$.dbTransactor(Deploy.scala:29)
```

The line in question is

```scala
  def dbTransactor: Transactor[Task] = DriverManagerTransactor[Task](
    "org.postgresql.Driver", Environment.jdbcUrl, Environment.dbUsername, Environment.dbPassword )

```

**Comment by tpolecat** [comment]
Hmm, which version of sbt are you using?

**Comment by tpolecat** [comment]
I think you need 0.13.13 or later because it's compiled with the typelevel compiler and sbt does some nonsense to sort out which scala-library jar to use.

**Comment by toby5box** [comment]
Thanks for the superfast response! 
I'm using 0.13.13 but I'll try 0.13.15. I had some problems with .15 on other projects.

**Comment by tpolecat** [comment]
Can you check to be sure you're not referring to `org.scala-lang` explicitly in your build? If so replace it with`scalaOrganization.value`.

**Comment by toby5box** [comment]
I'm not, as far as I can see; but you were 100% correct, moving to 0.13.15 made the problem disappear. Thanks!

(This is my first doobie project for `$work`. Woo!)

**Comment by tpolecat** [comment]
Whew 💦 

Let me know if I can help with anything else. You know where to find me.
