### ISSUE TITLE
support connection pool 

### ISSUE THREAD

**Issue by doriwal** [tpolecat/doobie#609]
I am  trying to use HukariCP according to 
https://tpolecat.github.io/doobie-0.2.2/12-Managing-Connections.html

doobie  version is 0.4.2 
doobie-contrib-hikari version is 0.3.0

I get error in runtime 

Exception in thread "main" java.lang.NoSuchMethodError: doobie.util.transactor$Transactor.<init>(Lscalaz/Monad;Lscalaz/Catchable;Ldoobie/util/capture$Capture;)V
    at doobie.contrib.hikari.hikaritransactor$HikariTransactor.<init>(HikariTransactor.scala:12)
    at doobie.contrib.hikari.hikaritransactor$HikariTransactor$$anonfun$initial$1.apply(HikariTransactor.scala:28)
    at doobie.contrib.hikari.hikaritransactor$HikariTransactor$$anonfun$initial$1.apply(HikariTransactor.scala:28)
    at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:339)
    at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:339)
    at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$7.apply(Task.scala:347)
    at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$7.apply(Task.scala:347)
    at scalaz.concurrent.Task$.Try(Task.scala:457)
    at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:347)
    at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:347)
    at scalaz.concurrent.Future.step(Future.scala:119)
    at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
    at scalaz.concurrent.Future.unsafePerformAsync(Future.scala:159)
    at scalaz.concurrent.Future.unsafePerformSync(Future.scala:184)
    at scalaz.concurrent.Task.unsafePerformSync(Task.scala:99)
...
what am I doing wrong ? 
This is my code 

object Test extends App {
  import doobie.imports._
  import scalaz.concurrent.Task
  import doobie.contrib.hikari.hikaritransactor._
  import doobie.imports._, scalaz._, Scalaz._, scalaz.concurrent.Task

 val q = sql"select * from monitoring.myTable".query[MonitoringRow].list

 private val p = for {
           xa <- HikariTransactor[Task]("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3600/monitoring", "xxx", "ppp")
           a <- q.transact(xa) ensuring xa.shutdown
  } yield xa
  p.unsafePerformSync

}

also does doobie create-close db connection by default after each query  ?

**Comment by tpolecat** [comment]
You must use the same version of both modules. So try doobie-contrib-hikari 0.4.2

And yes, `Transactor` by default will ensure that the connection is closed.

**Comment by doriwal** [comment]
can you please add link to doobie-contrib-hikari 0.4.2
the latest version in maven repo is 0.3.0

https://mvnrepository.com/artifact/org.tpolecat/doobie-contrib-hikari_2.11

**Comment by ChristopherDavenport** [comment]
Cats or Scalaz? 
I am not definitiive however so hopefully someone can say whether I'm right.

For Cats - 
[doobie-hikari-cats 0.4.4](http://search.maven.org/#artifactdetails%7Corg.tpolecat%7Cdoobie-hikari-cats_2.12%7C0.4.4%7Cjar)
[0.4.3](http://search.maven.org/#artifactdetails%7Corg.tpolecat%7Cdoobie-hikari-cats_2.12%7C0.4.2%7Cjar)

For Scalaz - 
[doobie-hikari 0.4.4](http://search.maven.org/#artifactdetails%7Corg.tpolecat%7Cdoobie-hikari_2.11%7C0.4.4%7Cjar)
[0.4.2](http://search.maven.org/#artifactdetails%7Corg.tpolecat%7Cdoobie-hikari_2.11%7C0.4.2%7Cjar)

**Comment by tpolecat** [comment]
Yes, sorry. The artifacts names changed in 0.4.0 … see the third bullet point [here](https://github.com/tpolecat/doobie/blob/series/0.5.x/CHANGELOG.md#changes-to-add-on-modules).

**Comment by tpolecat** [comment]
The artifact is called `doobie-hikari` now.
