### ISSUE TITLE
NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z

### ISSUE THREAD

**Issue by fanf** [tpolecat/doobie#711]
Hello,

I'm getting the below error with Doobie 0.5.1 / scala 2.12.4: 
```
java.lang.NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z
   at scala.reflect.internal.TypeDebugging$typeDebug$.<init>(TypeDebugging.scala:62)
   at scala.reflect.internal.SymbolTable.typeDebug$lzycompute$1(SymbolTable.scala:16)
   at scala.reflect.internal.SymbolTable.typeDebug(SymbolTable.scala:16)
   at scala.reflect.runtime.JavaUniverseForce.force(JavaUniverseForce.scala:54)
   at scala.reflect.runtime.JavaUniverseForce.force$(JavaUniverseForce.scala:6)
   at scala.reflect.runtime.JavaUniverse.force(JavaUniverse.scala:18)
   at scala.reflect.runtime.JavaUniverse.init(JavaUniverse.scala:150)
   at scala.reflect.runtime.JavaUniverse.<init>(JavaUniverse.scala:81)
   at scala.reflect.runtime.package$.universe$lzycompute(package.scala:17)
   at scala.reflect.runtime.package$.universe(package.scala:17)
   at doobie.util.meta$MetaInstances.$init$(meta.scala:428)
   at doobie.util.meta$Meta$.<init>(meta.scala:222)
   at doobie.util.meta$Meta$.<clinit>(meta.scala)
   at doobie.Modules.$init$(aliases.scala:28)
   at doobie.package$.<init>(package.scala:15)
   at doobie.package$.<clinit>(package.scala)
   at com.normation.rudder.db.Doobie$.<init>(Doobie.scala:79)  <= here, I have in code:  LogHandler { ...
```

So, I'm aware of https://github.com/tpolecat/doobie/issues/562 and of https://github.com/tpolecat/doobie/issues/568

I also read anything I found (the referenced gitter and etc), but I don't see how to solve the problem. 
[ok I found it - posting to help other if possible]

So, my set-up is a bit more complexe than most presented here, and the problem appeared with a plugin. 

The problem appeared to be that my main application was compiled with `org.slf4j:slf4j-api:jar:1.7.25`.
That dependency is marked as `provided` in the plugin, but somehow, maven (yes, I use maven - at that point, it's by pure masochism) toughout it makes perfect sense to use version from a transcient dependency from an other jar to compile the plugin: `org.slf4j:slf4j-api:jar:1.7.16`

So I ended with two incompatible version of `slf4j-api` used, and it grought in the very unexpected way above. 

Excluding the transcient `slf4j-api` dependency solved the problem.

**Comment by fanf** [comment]
The issue can be closed.

**Comment by tpolecat** [comment]
Are you using the typelevel compiler?

**Comment by fanf** [comment]
Not at all. Pure simple scala. Homogeneous version. 
http4s as a test dependency of the modul (version 0.18.1). Cats ecosystem 1.0.1. 
The problem seems really linked to the double slf4j-api on the path.

**Comment by fanf** [comment]
To be more precise: when the plugin was packaged, the bad version of slf4j-api was packaged in it (which doesn't make any sense to me, since maven DOES see it as provided, and it's a transcient dependency, but still). So there really was two differente classes of `slf4j-api` on the path, and so the classpath being what it is, one was chosen at random - certainly the one causing the most trouble by default, randomness being what it is.

**Comment by tpolecat** [comment]
Hm. Curious. slf4j is a Java lib so I'm puzzled that it matters.

**Comment by fanf** [comment]
I will try to see if I understand the why latter this night. I'm as
surprised as you, I spent quite some time trying to understand what was
wrong in the scala part of the dependencies.

Le mer. 11 avr. 2018 à 19:17, Rob Norris <notifications@github.com> a
écrit :
