### ISSUE TITLE
Support for Google BigQuery JDBC Driver.

### ISSUE THREAD

**Issue by wjlow** [tpolecat/doobie#767]
Google BigQuery has a JDBC Driver: https://cloud.google.com/bigquery/partners/simba-drivers/

I'm having trouble getting it to work with Doobie. 

I'm unsure if this is a problem with Doobie or with the Driver.

```
import cats.effect.IO
import doobie.implicits._
import doobie.util.transactor.Transactor

object Blah {
  
  val xa = Transactor.fromDriverManager[IO](
    "com.simba.googlebigquery.jdbc42.Driver", "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=rea-gcp-cia-dev;OAuthType=0;OAuthServiceAcctEmail=email@blah.gserviceaccount.com;OAuthPvtKeyPath=./some-service-account.json;", "", ""
  )
  val y = xa.yolo
  import y._

  def foo =
    sql"select id, name from country".query[(String, String, String)].check.unsafeRunSync

}
```

Running it in sbt console:

```
scala> foo
java.sql.SQLException: [Simba][JDBC](11680) Cannot use rollback while Connection is in auto-commit mode.
  at com.simba.googlebigquery.exceptions.ExceptionConverter.toSQLException(Unknown Source)
  at com.simba.googlebigquery.jdbc.common.SConnection.rollback(Unknown Source)
  at doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$rollback$1(kleisliinterpreter.scala:643)
  at doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$rollback$1$adapted(kleisliinterpreter.scala:643)
  at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:99)
  at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:176)
  at cats.effect.IO.unsafeRunTimed(IO.scala:321)
  at cats.effect.IO.unsafeRunSync(IO.scala:240)
  at mycode.Blah$.foo(Blah.scala:20)
  ... 36 elided
```

I have these libraries:

```
libraryDependencies ++= Seq(
  "org.typelevel" %% "cats-effect" % "1.0.0-RC3",
  "com.google.api-client" % "google-api-client" % "1.25.0",
  "com.google.apis" % "google-api-services-bigquery" % "v2-rev402-1.25.0",
  "com.google.api.client" % "google-api-client-googleapis" % "1.4.1-beta",
  "com.google.api.client" % "google-api-client-json" % "1.1.0-alpha",
  "org.tpolecat" %% "doobie-core" % "0.5.3"
)
```

Has anyone tried getting this to work? I don't understand Doobie or JDBC Drivers well enough to provide more information. :/

**Comment by wjlow** [comment]
Update: I got this to work!

I had to do 

```
xa.copy(strategy0 = Strategy.void)
```

to change the `Strategy`.

Now I get:

```
  select id, name from country

  ✕ SQL Compiles and Typechecks
    - [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: 400 Bad
      Request
  {
   "code" : 400,
   "errors" : [ {
   "domain" : "global",
   "location" :
      "country",
   "locationType" : "other",
   "message" : "Table name \"country\"
      cannot be resolved: dataset name is missing.",
   "reason" : "invalid"
   } ],

      "message" : "Table name \"country\" cannot be resolved: dataset name is
      missing."
  }
```

Is it worth documenting this anywhere? Or is it too specific to BigQuery?

**Comment by tpolecat** [comment]
You probably don't want `Strategy.void` … I think you want the void strategy with `always` set to `HC.close` to ensure you don't leak connections.

I'm not sure what the error message means. Do you expect that query to work?
